name: Build EXE

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet de lancer manuellement depuis l'onglet Actions

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt pip install -r requirements.txt
          pip install pyinstaller

      - name: Compilation en EXE
        run: |
          pyinstaller --onefile --noconsole main.py
        # Remplace "main.py" par le fichier principal de ton app

      - name: Upload de l'EXE compilé
        uses: actions/upload-artifact@v4
        with:
          name: Operateur112-exe
          path: dist/*.exe
